name: Create and Rename Directory

on:
  push:
    branches:
      - master

jobs:
  create_directory:
    runs-on: ubuntu-latest
    steps:
      - name: Create directory
        run: mkdir mydir
  rename_directory:
    runs-on: ubuntu-latest
    needs: [create_directory]
    steps: 
      - name: Rename directory to main
        run: mv mydir main
